server:
  port: 8799
spring:
  application:
    name: securitys
  datasource:
    password: huongson1
    url: jdbc:postgresql://localhost:5555/qlbh_user_test
    username: Administration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
keycloak:
  security-constraints:
  - auth-roles: user
  - security-collections:
    - patterns: /users/*
  auth-server-url: http://localhost:8080/auth
  realm: Dungnv
  resource: login-app
  public-client: true
  principal-attribute: user-test-spring
